xcassets:
    inputs: Sources/AdmiralTabsSwiftUI/Resources/Assets/Images.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: Sources/AdmiralTabsSwiftUI/Assets/Images.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: Images
