xcassets:
    inputs: AdmiralUTabsViewer/AdmiralUTabsViewer/Assets.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: AdmiralUTabsViewer/AdmiralUTabsViewer/Resources/Assets.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: Assets
